var data = `[{"id":1,"name":"Kenneth","username":"Olson","date":"1/16/2016","content":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","pic":"http://dummyimage.com/60x60.jpg/dddddd/000000"},
{"id":2,"name":"Kathleen","username":"Lane","date":"3/13/2016","content":"Phasellus in felis. Donec semper sapien a libero. Nam dui.","pic":"http://dummyimage.com/60x60.png/cc0000/ffffff"},
{"id":3,"name":"Mildred","username":"Allen","date":"2/21/2016","content":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff"},
{"id":4,"name":"Shawn","username":"Burns","date":"7/24/2016","content":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","pic":"http://dummyimage.com/60x60.png/5fa2dd/ffffff"},
{"id":5,"name":"Terry","username":"Larson","date":"2/7/2016","content":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.","pic":"http://dummyimage.com/60x60.bmp/5fa2dd/ffffff"},
{"id":6,"name":"Terry","username":"Welch","date":"7/8/2016","content":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","pic":"http://dummyimage.com/60x60.png/dddddd/000000"},
{"id":7,"name":"Ryan","username":"Dixon","date":"1/4/2016","content":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.","pic":"http://dummyimage.com/60x60.png/ff4444/ffffff"},
{"id":8,"name":"George","username":"Ruiz","date":"4/23/2016","content":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","pic":"http://dummyimage.com/60x60.bmp/ff4444/ffffff"},
{"id":9,"name":"Rachel","username":"Reynolds","date":"10/6/2015","content":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","pic":"http://dummyimage.com/60x60.bmp/ff4444/ffffff"},
{"id":10,"name":"Lori","username":"Gardner","date":"11/4/2015","content":"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","pic":"http://dummyimage.com/60x60.bmp/cc0000/ffffff"},
{"id":11,"name":"Kenneth","username":"Wright","date":"9/11/2015","content":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","pic":"http://dummyimage.com/60x60.png/5fa2dd/ffffff"},
{"id":12,"name":"Amanda","username":"Lane","date":"12/13/2015","content":"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","pic":"http://dummyimage.com/60x60.bmp/dddddd/000000"},
{"id":13,"name":"Theresa","username":"Vasquez","date":"9/11/2015","content":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","pic":"http://dummyimage.com/60x60.jpg/dddddd/000000"},
{"id":14,"name":"Ryan","username":"Wells","date":"7/29/2016","content":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","pic":"http://dummyimage.com/60x60.png/cc0000/ffffff"},
{"id":15,"name":"Bruce","username":"Russell","date":"12/6/2015","content":"Fusce consequat. Nulla nisl. Nunc nisl.","pic":"http://dummyimage.com/60x60.png/cc0000/ffffff"},
{"id":16,"name":"Lois","username":"Schmidt","date":"10/15/2015","content":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","pic":"http://dummyimage.com/60x60.bmp/5fa2dd/ffffff"},
{"id":17,"name":"Carolyn","username":"Ward","date":"4/1/2016","content":"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","pic":"http://dummyimage.com/60x60.jpg/dddddd/000000"},
{"id":18,"name":"Matthew","username":"Dunn","date":"3/2/2016","content":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","pic":"http://dummyimage.com/60x60.bmp/5fa2dd/ffffff"},
{"id":19,"name":"Laura","username":"Moore","date":"10/23/2015","content":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","pic":"http://dummyimage.com/60x60.bmp/dddddd/000000"},
{"id":20,"name":"Beverly","username":"Brown","date":"5/10/2016","content":"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff"}]`;


// preserve newlines, etc - use valid JSON
data = data.replace(/\\n/g, "\\n")
              .replace(/\\'/g, "\\'")
              .replace(/\\"/g, '\\"')
              .replace(/\\&/g, "\\&")
              .replace(/\\r/g, "\\r")
              .replace(/\\t/g, "\\t")
              .replace(/\\b/g, "\\b")
              .replace(/\\f/g, "\\f");
// remove non-printable and other non-valid JSON chars
data = data.replace(/[\u0000-\u0019]+/g,"");
