var data = `[{"id":"0c5076fb-5fbe-4cd1-b397-a3153aaeea9e","name":"Paula","username":"pknight0","date":"7/13/2016","content":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","pic":"http://dummyimage.com/60x60.png/ff4444/ffffff","tweetid":"11410-011"},
{"id":"9985cc8a-2c20-4026-8b63-1c3f41e5f9a6","name":"Christine","username":"cgray1","date":"4/19/2016","content":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","pic":"http://dummyimage.com/60x60.png/ff4444/ffffff","tweetid":"10096-0279"},
{"id":"93930294-85a5-4cbd-953c-6bbd49e3daf8","name":"Donald","username":"dstevens2","date":"11/23/2015","content":"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","pic":"http://dummyimage.com/60x60.png/cc0000/ffffff","tweetid":"49967-384"},
{"id":"6a756e08-bbfa-47f1-ad3d-d437b2f857f5","name":"Matthew","username":"mgonzales3","date":"9/17/2015","content":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.","pic":"http://dummyimage.com/60x60.png/5fa2dd/ffffff","tweetid":"56062-485"},
{"id":"e1693c42-01ce-4c67-9039-384a25c689ad","name":"Sarah","username":"sboyd4","date":"7/23/2016","content":"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","pic":"http://dummyimage.com/60x60.jpg/dddddd/000000","tweetid":"10736-012"},
{"id":"56b43242-1cc6-470a-9a20-24d16e404913","name":"Karen","username":"kgarrett5","date":"10/25/2015","content":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","pic":"http://dummyimage.com/60x60.png/dddddd/000000","tweetid":"57844-324"},
{"id":"108e2206-ab90-4a15-ad87-0fc375be6b9c","name":"Larry","username":"lpayne6","date":"4/23/2016","content":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.","pic":"http://dummyimage.com/60x60.bmp/cc0000/ffffff","tweetid":"0378-4003"},
{"id":"ae599ce8-4cba-46b1-b09e-5f63dcda2935","name":"Teresa","username":"tstanley7","date":"12/15/2015","content":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","pic":"http://dummyimage.com/60x60.jpg/ff4444/ffffff","tweetid":"0462-0395"},
{"id":"3262f77b-3ca4-44f8-a9a9-289f584dd884","name":"Janice","username":"jmoore8","date":"9/23/2015","content":"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff","tweetid":"54575-134"},
{"id":"a8cf1228-ee44-46f1-ac4d-2445731050c7","name":"Kimberly","username":"kriley9","date":"2/1/2016","content":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","pic":"http://dummyimage.com/60x60.jpg/cc0000/ffffff","tweetid":"36987-2806"},
{"id":"6373fd39-30d1-4cb3-a34b-070d70722922","name":"Daniel","username":"dbrowna","date":"9/11/2015","content":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","pic":"http://dummyimage.com/60x60.png/dddddd/000000","tweetid":"53489-406"},
{"id":"c1c5d8a0-f42d-4559-b3b8-c06cb5276906","name":"Sharon","username":"spriceb","date":"5/2/2016","content":"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff","tweetid":"49349-725"},
{"id":"0719dcf8-fba6-4517-873d-fa4e55ac2575","name":"Jeremy","username":"jlawsonc","date":"6/25/2016","content":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","pic":"http://dummyimage.com/60x60.bmp/5fa2dd/ffffff","tweetid":"43063-214"},
{"id":"59e02625-d854-4e69-a1f4-458992b86186","name":"Robin","username":"revansd","date":"7/2/2016","content":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff","tweetid":"42549-645"},
{"id":"e6cc346c-d729-4430-82ae-e1b9925fad35","name":"Diana","username":"dwagnere","date":"12/25/2015","content":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","pic":"http://dummyimage.com/60x60.png/5fa2dd/ffffff","tweetid":"54235-207"},
{"id":"fc1046bf-e8c5-4a1a-a984-aefc51e53a4d","name":"Joseph","username":"jsimsf","date":"1/15/2016","content":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","pic":"http://dummyimage.com/60x60.jpg/cc0000/ffffff","tweetid":"16590-006"},
{"id":"e9f9f24f-bf73-426d-9cc0-11b5612882b8","name":"Joan","username":"jwellsg","date":"4/6/2016","content":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","pic":"http://dummyimage.com/60x60.bmp/5fa2dd/ffffff","tweetid":"57894-060"},
{"id":"44430409-c8a2-4ef7-a2fd-4d8704a5667e","name":"Karen","username":"kallenh","date":"8/15/2016","content":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","pic":"http://dummyimage.com/60x60.png/ff4444/ffffff","tweetid":"47242-0001"},
{"id":"017a2990-fa2d-4c8a-9225-234678762f55","name":"Melissa","username":"mmedinai","date":"4/28/2016","content":"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff","tweetid":"0185-0144"},
{"id":"180b17d0-e849-409c-9849-33a88423e85e","name":"Jessica","username":"jpalmerj","date":"8/8/2016","content":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","pic":"http://dummyimage.com/60x60.jpg/cc0000/ffffff","tweetid":"0113-0685"},
{"id":"66eb2281-c0fc-4d65-b425-ae601e6c401b","name":"Amanda","username":"aharveyk","date":"7/1/2016","content":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff","tweetid":"0268-0898"},
{"id":"dc782d35-e63c-4593-8574-10d6197eaaae","name":"Andrew","username":"awrightl","date":"6/13/2016","content":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","pic":"http://dummyimage.com/60x60.bmp/dddddd/000000","tweetid":"63629-5042"},
{"id":"f2f96c70-0882-4fec-b569-3b491cd418d8","name":"Paula","username":"pbryantm","date":"2/6/2016","content":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff","tweetid":"0378-1077"},
{"id":"a01a92e8-d175-4408-b397-fa05a51ceb85","name":"Timothy","username":"trobinsonn","date":"9/6/2016","content":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","pic":"http://dummyimage.com/60x60.png/dddddd/000000","tweetid":"41250-023"},
{"id":"75f35310-6faa-42ff-a8d3-22e87101193b","name":"Beverly","username":"brileyo","date":"1/22/2016","content":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff","tweetid":"43478-245"},
{"id":"dbf200cb-fa91-4cce-b585-ba488916e3fc","name":"Andrea","username":"agibsonp","date":"4/14/2016","content":"Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.","pic":"http://dummyimage.com/60x60.bmp/ff4444/ffffff","tweetid":"54868-6279"},
{"id":"67cf133d-56aa-4649-91c9-aec716782937","name":"Teresa","username":"twestq","date":"1/17/2016","content":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.","pic":"http://dummyimage.com/60x60.jpg/dddddd/000000","tweetid":"63824-271"},
{"id":"b50aa5ec-2d29-49ea-9ec2-e520a092cdd8","name":"Andrew","username":"amatthewsr","date":"12/6/2015","content":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","pic":"http://dummyimage.com/60x60.bmp/cc0000/ffffff","tweetid":"42254-176"},
{"id":"0af91d93-0a31-4a55-9b91-8fdd662852ac","name":"Randy","username":"rwilliamsons","date":"4/21/2016","content":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","pic":"http://dummyimage.com/60x60.bmp/ff4444/ffffff","tweetid":"68094-720"},
{"id":"e757df4e-282b-419b-9fd5-575c039d4eae","name":"Walter","username":"wparkert","date":"8/28/2016","content":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","pic":"http://dummyimage.com/60x60.jpg/dddddd/000000","tweetid":"68791-102"},
{"id":"67e5a34a-80f9-44a7-9df4-65075f2c1f5e","name":"Douglas","username":"dcarpenteru","date":"11/23/2015","content":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","pic":"http://dummyimage.com/60x60.jpg/ff4444/ffffff","tweetid":"25225-018"},
{"id":"35b338b1-ddb3-4aba-8344-b3bf67ff9d21","name":"Stephanie","username":"smeyerv","date":"7/16/2016","content":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.","pic":"http://dummyimage.com/60x60.bmp/cc0000/ffffff","tweetid":"13826-001"},
{"id":"22469da3-3d8b-4074-8fd4-93d93bc0a1d5","name":"Aaron","username":"arossw","date":"6/17/2016","content":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","pic":"http://dummyimage.com/60x60.jpg/cc0000/ffffff","tweetid":"41520-403"},
{"id":"d9a30233-8232-4264-9785-b7a0a32e5fdc","name":"Benjamin","username":"bwardx","date":"9/29/2015","content":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","pic":"http://dummyimage.com/60x60.png/cc0000/ffffff","tweetid":"0113-0660"},
{"id":"8dbdb7bd-08f8-4c4c-9d06-f9f37b6e11a3","name":"Elizabeth","username":"ehernandezy","date":"5/19/2016","content":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","pic":"http://dummyimage.com/60x60.png/cc0000/ffffff","tweetid":"55316-467"},
{"id":"70710837-cec6-447a-9c83-155cdee56992","name":"Martha","username":"mnelsonz","date":"8/1/2016","content":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.","pic":"http://dummyimage.com/60x60.png/cc0000/ffffff","tweetid":"67979-501"},
{"id":"6008009f-a048-43c2-8b95-861c08f9c729","name":"Antonio","username":"acarpenter10","date":"4/26/2016","content":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.","pic":"http://dummyimage.com/60x60.bmp/ff4444/ffffff","tweetid":"57955-0161"},
{"id":"7345998f-3aa9-4777-b67a-5072e985b8a8","name":"Robert","username":"rrobinson11","date":"3/20/2016","content":"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.","pic":"http://dummyimage.com/60x60.png/5fa2dd/ffffff","tweetid":"55316-194"},
{"id":"49b0c28f-e0d4-4992-ba73-20f3ea1e6569","name":"Mildred","username":"mevans12","date":"6/27/2016","content":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.","pic":"http://dummyimage.com/60x60.png/cc0000/ffffff","tweetid":"66467-2004"},
{"id":"1fe7f08f-b57c-4b2f-b36e-06f86e2885a3","name":"Billy","username":"bhenry13","date":"2/9/2016","content":"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff","tweetid":"59050-434"},
{"id":"09863571-5153-4ac5-a09d-d406786f208f","name":"Mary","username":"mcarr14","date":"7/15/2016","content":"Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","pic":"http://dummyimage.com/60x60.png/ff4444/ffffff","tweetid":"45942-1629"},
{"id":"e3180bac-917e-4041-85e9-d75000a6c7d9","name":"Timothy","username":"troberts15","date":"6/18/2016","content":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","pic":"http://dummyimage.com/60x60.png/ff4444/ffffff","tweetid":"41520-345"},
{"id":"9dd3c688-ffb4-44e4-bd5e-8db7a8a9aba5","name":"Marilyn","username":"mromero16","date":"2/6/2016","content":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","pic":"http://dummyimage.com/60x60.bmp/5fa2dd/ffffff","tweetid":"42221-0012"},
{"id":"b7336d15-7f58-48e0-9776-b66e3b3c6760","name":"George","username":"gcrawford17","date":"8/6/2016","content":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","pic":"http://dummyimage.com/60x60.jpg/dddddd/000000","tweetid":"41616-219"},
{"id":"be682778-8e0a-4d40-8bc9-b89446b59e62","name":"Clarence","username":"cperez18","date":"4/28/2016","content":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","pic":"http://dummyimage.com/60x60.jpg/cc0000/ffffff","tweetid":"10019-925"},
{"id":"50b275c2-7831-4fe1-be16-f2d892d6a20e","name":"Christopher","username":"cbell19","date":"8/17/2016","content":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","pic":"http://dummyimage.com/60x60.png/ff4444/ffffff","tweetid":"55714-4501"},
{"id":"53511580-f628-49e8-b0d8-79f93f59071f","name":"Donna","username":"dhudson1a","date":"12/3/2015","content":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","pic":"http://dummyimage.com/60x60.png/dddddd/000000","tweetid":"0378-6163"},
{"id":"8ac8a783-9fe8-4b8c-a7ab-874ed1ae2af6","name":"Rachel","username":"rpatterson1b","date":"10/26/2015","content":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","pic":"http://dummyimage.com/60x60.jpg/5fa2dd/ffffff","tweetid":"42507-977"},
{"id":"4ec43bf2-8316-4226-853a-c0b6fa084a43","name":"Amy","username":"awillis1c","date":"8/3/2016","content":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","pic":"http://dummyimage.com/60x60.bmp/ff4444/ffffff","tweetid":"10167-400"},
{"id":"fbc84d2f-7f42-4a56-a539-09a4c28cb539","name":"Beverly","username":"bchavez1d","date":"5/20/2016","content":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","pic":"http://dummyimage.com/60x60.jpg/dddddd/000000","tweetid":"36987-1381"}]`;


// preserve newlines, etc - use valid JSON
data = data.replace(/\\n/g, "\\n")
              .replace(/\\'/g, "\\'")
              .replace(/\\"/g, '\\"')
              .replace(/\\&/g, "\\&")
              .replace(/\\r/g, "\\r")
              .replace(/\\t/g, "\\t")
              .replace(/\\b/g, "\\b")
              .replace(/\\f/g, "\\f");
// remove non-printable and other non-valid JSON chars
data = data.replace(/[\u0000-\u0019]+/g,"");
